### ISSUE TITLE
features and a bug

### ISSUE THREAD

**Issue by somestrangethings** [PhieF/CarnetAndroid#10]
Hey! 

I like the carnet app! But there are some questions as well.

Features:
1. Is there a way to sync via owncloud? 
If not, will it be possible, soon?
2. Can you add the possibility to delete  keywords? 
3. What do you think about a dark theme?
4. And what about the possibility to give notes different colours? (As backgroundcolour or framecolour on "recents", for example.)

A bug, I guess: 
When I paste a text into a (text-)note carnet shows me the upper part of the file. The same happens when I mark a word (or more) and click some format-button. 
If I use the cursor keys carnet returns to the correct part of the file and I can continue writing my text. But if I do something else instead of using the cursor keys first (for lack of concentration or time) I have to search through the whole text to find the passage I want to work on. That's really annoying! 

Donation:
Is there another way to donate?

**Comment by PhieF** [comment]
Yep since with owncloud should also work (see that in settings, owncloud = nextcloud)
selecting the keyword when you"re editing a note should delete the keyword

Dark theme, why not ! I will add this to my todo list
the notes color is something I'd like to add too

I've noticed some focus issues like you said, I will try to work on that !

I've opened a liberapay account, but this is for weekly donation (even very small donations)
I will perhaps open an account on paypal or something like that

Thanks for your report !

**Comment by somestrangethings** [comment]
My ownCloud is shown at "Account list" so I think sync should work.

But I can't find a way to change "Remote folder": 
Settings --> Sync with cloud storage --> Account list (my ownCloud-account) --> AccountConfigActivity: There's "Remote folder" and a backslash. Tap it --> "Pick folder", tap on it --> and I'm back at "AccountConfigActivity". Sorry, but, I don't understand that. And what is that envelope-button for? Nothing happens when I tap it. That's confusing me. 

Carnet stores my notes on my phone, but doesn't sync the folder with my ownCloud-account, and there seems to be no way to choose the folder on internal storage as the folder that should be synced. Why?

**Comment by PhieF** [comment]
Hm perhaps nextcloud api isn't compatible with owncloud, I will have to try that
Is it possible to create me an owncloud account on your server ? If you can't I will deploy my own server, 

thanks

**Comment by somestrangethings** [comment]
Now I'm using NextCloud and that works.

**Comment by PhieF** [comment]
OK, great ! I haven't tested it with own cloud. I will soon implement webdav-only sync
