### ISSUE TITLE
[Feature Request] Make dark theme for entire app

### ISSUE THREAD

**Issue by PopeRigby** [PhieF/CarnetAndroid#23]
Right now it only effects the main screen. Not the settings or lock menu.

**Comment by somestrangethings** [comment]
I'm happy to find that there's a dark theme now. Not perfect, yet, but it's a dark theme! :-) Some details "disappear" because of the dark theme. Existing keywords in the keywords list, for example. A gray Ok-Button on a dark background is not that good, too.

**Comment by PhieF** [comment]
Pin code is now dark, I've also fixed dialogues

settings will remain white if you don't mind, because that's the theme I'm using and at least I'm sure people will be able to access it in case of issues

thanks for your reports and sorry for the late reply ! :)
