### ISSUE TITLE
Android Pie can't create/open item, cleartext not permitted

### ISSUE THREAD

**Issue by versd** [PhieF/CarnetAndroid#27]
Dev, great app! This is exactly what I was missing.

When creating an item, or opening an existing item, it just shows "Loading..." indefinitely. I found that I can select invisible text on the page, which says the following:

```
Webpage not available
The webpage at http://localhost:39586/tmp/reader.html" could not be loaded because: 
net::ERR_CLEARTEXT_NOT_PERMITTED
```
I'm assuming this is due to changes in android API 28 .
See [this post](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted/50834600#50834600) for a possible workaround.

**Comment by PhieF** [comment]
It should be working, now. Can you confirm ?

Thanks !
