### ISSUE TITLE
can't open Carnet

### ISSUE THREAD

**Issue by somestrangethings** [PhieF/CarnetAndroid#34]
Hey there!
I used carnet a few hours today but then it closed, I don't know why. I tried "wipe cache partition", restarted my phone, deleted the carnet cache, restarted my phone again, but carnet doesn't start. 

I'm using Oreo 8.0 on Samsung S7.

Regards!

**Comment by somestrangethings** [comment]
My phone is not rooted and I don't want to root it. And I don't know how to use adb. I don't even have a notebook or computer so it isn't possible for me to root my phone and so on. ;-) 

Regards!

**Comment by PhieF** [comment]
Hm.

Could you make a copy of the folder /sdward/QuickNote and then wipe Carnet's storage ?

**Comment by shawn1thompson** [comment]
Would a bug report help?

**Comment by PhieF** [comment]
That's... a weird bug, but I'm not sure this is the same as the one of @somestrangethings

**Comment by shawn1thompson** [comment]
Should I open a new issue?

**Comment by PhieF** [comment]
@shawn1thompson I guess I've just fixed your bug. Do you use the fdroid or google play version ?

**Comment by shawn1thompson** [comment]
It appears you have. I use the F-Droid version and have updated. The only cosmetic issue is that it show .sqd in the name of the note on Android.

**Comment by PhieF** [comment]
yep, it will be fixed to  ! :)
