### ISSUE TITLE
Browser not updating after sync

### ISSUE THREAD

**Issue by hyphone** [PhieF/CarnetAndroid#35]
Hello and good day,

when a note was changed on the desktop and synced and I'm in the browser view on the other device the changes won't be seen until I go to the browser again.
There is a chance of overwriting the latest changes:
- both devices in browser view
- one device changes a note
- both devices sync
- the changes are only seen when going explicitly to the browser again, if not the old version opens
   - if I then hit exit to exit the note, the changes are overwritten with the older version and synced again

expected behavior: the changes are seen immediatley on the other device

EDIT: this was in the F-DROID version. I installed the version from the playstore and the problem does not exist there
The Browser view does indeed not update automatically but the corresponding note was the new one when I opened it.

**Comment by PhieF** [comment]
That's right, thanks for the bug report

**Comment by PhieF** [comment]
fixed #fbddb8c558ffd723d43ae3885aaedcaf21749289
