### ISSUE TITLE
 Allow notes to have a date set in addition to default created/modified date

### ISSUE THREAD

**Issue by antonizoon** [PhieF/CarnetAndroid#36]
I'm hoping to use Carnet as a replacement for the Android App Journey, which aims to make a Markdown based photojournal recording onto cloud storage.

Since journey is both proprietary and uses Google Drive, I was trying Carnet as an alternative, and it is generally a sufficient replacement except for the fact that it does not allow an event date to be set.

Journey allows notes to have an Event Date so I can make notes about a certain time long after it has happened, and then it sorts notes by the Event Date. This is different from the current created/modified date, which can be retained as not modifiable.

In addition, Journey detects the Event Date from photos using exif data. This would also be a great feature to have.

**Comment by PhieF** [comment]
Hi, just an update to say that I haven"t forgotten this report and I'm working on this feature :)

**Comment by antonizoon** [comment]
Nice. The date feature is the most important, while date extraction from exif might be a bit harder but it's worth it.

**Comment by PhieF** [comment]
Implemented for next version,
And in the future I will add an "order" feature (not yet)
