### ISSUE TITLE
Changelog too fast to read

### ISSUE THREAD

**Issue by supermamie** [PhieF/CarnetAndroid#42]
When the app is updated, we only have 5sec to read the changelog, with no way to display it again.

On tap, the timer should stop, and the settings menu should have a button to open it again.

**Comment by realrufans** [comment]
Hahahahaha I usually take a screenshot 😝.
I don't know why it's so.

**Comment by PhieF** [comment]
Haha that's right, I will also add something in settings

**Comment by PhieF** [comment]
Fixed ! :)
