### ISSUE TITLE
Fix Nextcloud SSO with android 7 Note title with random letters?

### ISSUE THREAD

**Issue by realrufans** [PhieF/CarnetAndroid#45]
Hello PO, 
Thanks a lot for this great app. I love seeing updates 👌.

With this recent update, I seem not to understand it or couldn't notice any change.

I understand you fixed a bug?

**Comment by PhieF** [comment]
Hi !
Yes this was a bug fix release :)

**Comment by realrufans** [comment]
Oh that's awesome. Was the bug reported? If yes kindly reference it.

**Comment by PhieF** [comment]
the bug fix was

Fix Nextcloud SSO with android 7 
Note title with random letters

there was a missing line

https://github.com/PhieF/CarnetAndroid/issues/38

and the other was reported by mail
