### ISSUE TITLE
Intempestive saving makes naming a note difficult

### ISSUE THREAD

**Issue by Oygron** [PhieF/CarnetAndroid#46]
Hi,
When I want to name or rename a note in the side panel of an opened note, if I wait for a too long time (2sec) before typing the next letter, the app will save the note, and close the keyboard. It is thus a painful process as I'm not a fast writer on mobile.
Perhaps you should either wait for a longer time or wait until the field is not active anymore, or find a way so that the keyboard is not hidden each time. 
Thanks!

**Comment by PhieF** [comment]
Hi,

I've put a 10 seconds delay + when clicking outside of the text box, it should be better :)

thanks for your report !
