### ISSUE TITLE
The auto refresh when changing the title too fast.

### ISSUE THREAD

**Issue by dhsc19** [PhieF/CarnetAndroid#47]
When I try to rename the title, the screen refreshes so quickly if I don't type fast enough that the soft keyboard disappears and I have to tap on the title line again to continue typing.  Often this happens so many times just trying to finish typing a single word.

**Comment by PhieF** [comment]
Hi, do you have the v0.13 of the app ? I've already changed that

**Comment by dhsc19** [comment]
Ok.  Yeah, I have v0.13.  Just haven't been able to try it since the last
Carnet update for Nextcloud stopped working on my server.  Please close.
