### ISSUE TITLE
Android app not syncing with nextcloud app

### ISSUE THREAD

**Issue by Koantig** [PhieF/CarnetAndroid#55]
Hi,
I've got an issue similar to the one reported here: https://github.com/PhieF/CarnetAndroid/issues/29
I've installed the NC app (NC 13 , Carnet 0.14.0) and created a note 'From Web'.
I then installed the Android app (0.14.0, from F-droid), connected to my NC app by accepting the default username and address, which looked correct. I didn't have to enter my NC credentials.

I created a couple of notes from the Android app but I can't see them from NC and I can't see the note 'From Web' on Android.

`Documents/QuickNote` on NC only shows the 'From Web' note (as an .sqd file)

If I go to 'AccountConfigActivity' on the Android app, it shows the remote folder to be `Documents/QuickNote`, which seems correct. I'm beginning to think that it doesn't have the permission to access the folder because if I try to set it manually and click on the folder `Documents`, it tells me that the folder is empty.

Thank you in advance

**Comment by timbogithub** [comment]
Was having the same problems. 

Discovered that  "connected to my NC app by accepting the default username and address, which looked correct." did not work. 

Solution for me:

1. Delete NC Account from Carnet App
2. Shut down Carnet App
3. Open App, and add begin adding NC account, using the full wizard which asks whether you want to use Carnet Live test account first. 
4. DO NOT accept automatic account setup
5. Add account details and login. 
6. Voila - Carnet will connect and synch.

Worked for me. 

1.

**Comment by Koantig** [comment]
Thanks, using my NC server and entering my credentials did work.
(A bit uncomfortable to give my credentials to an app but I can live with it in this case. I'd prefer to give it access to the necessary folder only.)
