### ISSUE TITLE
Writing notes drains battery

### ISSUE THREAD

**Issue by melohr** [PhieF/CarnetAndroid#59]
Recently, I wrote a text for approximately 20 minutes. During this time, my battery app reported a drain rate of roughly 37% per hour. Could it be, that saving occurs continuously while writing? Could you optimize this (e.g. save only after a certain number of chars or time and/or open note is closed)?

**Comment by PhieF** [comment]
Hi, 

do you still have this issue ?

Sorry  for the late reply

**Comment by melohr** [comment]
@PhieF 
Hi,
No worries! I just checked and current consumption stays stable no matter if app is just opened or in edit mode. Thank you very much!
