### ISSUE TITLE
Todo-list behavior

### ISSUE THREAD

**Issue by metsuke0** [PhieF/CarnetAndroid#61]
My friend is attempting to use this app and they are very accustomed to the Google Keep method of dealing with checkbox lists.  The issue they run in to is that when they tap on a note to enter it, they accidentally check a "todo" item instead.  Keep does not check any items, but enters the note no matter where you tap.  Is there a way to add the option to not check any todo-list checkboxes when tapped, but rather enter the note instead?

**Comment by PhieF** [comment]
Yep, that's right ! That was something I wanted to "fix"

I will add it to my todo list ;)

thanks for the reminder

**Comment by PhieF** [comment]
already fixed
