### ISSUE TITLE
Update to 0.19.2 deleted data & endless loop

### ISSUE THREAD

**Issue by RufioHugo** [PhieF/CarnetAndroid#80]
Just updates to 0.19.2
- deleted all notes on phone
- deleted all notes on Next cloud
- every time it starts; installation routine & deletes all data/notes

= I'm not able to downgrade with "unknown error" (via F-Droid)

**Comment by toxpal** [comment]
It looks I have better luck. Even if I have exactly the issue, my installation routine doesn't delete existing notes (only settings). Hopefully dev will take care of this.

**Comment by Wrexthor** [comment]
same issue with infinite sync loop

**Comment by exomar** [comment]
To downgrade from fdroid you can first take backup with oandbackup then uninstall newer version then install previous version and try restore with data only from backup.

**Comment by toxpal** [comment]
You don't need to downgrade anymore, fix was pushed as new version in FDroid

**Comment by RufioHugo** [comment]
Yeah - just were a few days off and've seen it now! Thx
